defaultSemverRangePrefix: ""

nodeLinker: node-modules

packageExtensions:
  gatsby-plugin-image@2.13.0:
    peerDependencies:
      "@emotion/react": 11.10.0

yarnPath: .yarn/releases/yarn-3.2.4.cjs
