defaultSemverRangePrefix: ""

nodeLinker: node-modules

packageExtensions:
  gatsby-plugin-image@2.13.0:
    peerDependencies:
      "@emotion/react": 11.10.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
