defaultSemverRangePrefix: ""

nodeLinker: node-modules

# TODO: Gatsby 5 마이그레이션 후 제거 가능한지 확인
packageExtensions:
  gatsby-plugin-image@2.13.0:
    peerDependencies:
      "@emotion/react": 11.10.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
