defaultSemverRangePrefix: ""

packageExtensions:
  gatsby-plugin-image@2.13.0:
    peerDependencies:
      "@emotion/react": 11.10.0

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.3.cjs
