title: Beomy # your site title
lang: ko
author: Hyo Bum Lee
email: beomyhlee@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Beomy Develope Site
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://janczizikow.github.io/sleek" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  beomy # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
linkedin_username: 효범-이-930453134
tistory_username: beomy
social:
  name: Hyo Bum Lee
  links:
    - https://www.linkedin.com/in/효범-이-930453134
    - https://github.com/beomy

disqus:
  shortname: beomy # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-MK2RSFQ # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID
google_analytics: UA-144478158-1 # replace with your GA tracking identifier

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
