export { default as Button } from './Button';
export * from './Button';
export { default as Dim } from './Dim';
export * from './Dim';
export { default as Img } from './Img';
export * from './Img';
export { default as H1 } from './H1';
export * from './H1';
export { default as H2 } from './H2';
export * from './H2';
export { default as H4 } from './H4';
export * from './H4';
export { default as Li } from './Li';
export * from './Li';
export { default as P } from './P';
export * from './P';
export { default as Span } from './Span';
export * from './Span';
export { default as Ul } from './Ul';
export * from './Ul';
